#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DoLess.Localization.Sample.Droid.Resource", IsApplication=true)]

namespace DoLess.Localization.Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Message1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Message2 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Message3 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int String1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int String2 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int String3 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int String4 = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int String5 = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int String6 = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int String7 = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int String8 = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
